from __future__ import annotations

# Color Palette
PRIMARY_COLOR = "#0F766E"  # Teal accent
SUCCESS_COLOR = "#0EA26C"
WARNING_COLOR = "#F59E0B"
INFO_COLOR = "#2563EB"
BACKGROUND_COLOR = "#F7F8FB"
SURFACE_COLOR = "#FFFFFF"
BORDER_COLOR = "#E5E7EB"
TEXT_COLOR = "#111827"
TEXT_MUTED = "#6B7280"
WHITE = "#FFFFFF"
BLACK = "#0B1021"
GRAY = "#9CA3AF"

# Charting
CHART_FOCUS_COLOR = "#0F766E"
CHART_SECONDARY_COLOR = "#D1D5DB"
