import type { Metadata } from "next";
import Link from "next/link";

import { PageHero } from "@/components/page-hero";
import { SectionCard } from "@/components/section-card";

export const metadata: Metadata = {
  title: "Data Use | JamBandNerd",
  description:
    "How JamBandNerd uses public factual setlist information and its own derived analytics.",
};

const CONTACT_EMAIL = "jambandnerd2026@gmail.com";

export default function DataUsePage() {
  return (
    <div className="mx-auto max-w-5xl space-y-8">
      <PageHero
        kicker="Reference policy"
        eyebrow="Data use"
        title="Data Use"
        description="JamBandNerd is intended to present factual show information and its own derived analytics in a reference-style format. This page explains what the site uses and what it is designed not to reproduce."
      />

      <SectionCard title="What The Site Uses">
        <div className="space-y-3 text-sm leading-6 text-on-surface-variant">
          <p>Publicly available factual show information such as band names, show dates, venues, cities, regions, and song titles.</p>
          <p>Structured setlist-style metadata such as song order, basic show context, and historical occurrence patterns where publicly available.</p>
          <p>JamBandNerd’s own derived outputs, including prediction rankings, gap metrics, venue summaries, recall calculations, and other analytics generated by the site.</p>
        </div>
      </SectionCard>

      <div className="grid gap-4 md:grid-cols-2">
        <SectionCard title="What The Site Is Not Reproducing">
          <div className="space-y-3 text-sm leading-6 text-on-surface-variant">
            <p>No lyrics, sheet music, or notation.</p>
            <p>No audio or video files.</p>
            <p>No long-form editorial writeups, articles, or expressive source material copied onto the site.</p>
            <p>No paywalled or authenticated source content is intended to be republished here.</p>
          </div>
        </SectionCard>

        <SectionCard title="Good-Faith Product Intent">
          <div className="space-y-3 text-sm leading-6 text-on-surface-variant">
            <p>The site is meant to help users follow next-show predictions, compare historical outcomes, and explore venue or rotation patterns.</p>
            <p>The product is designed around factual reference data and internally generated analysis rather than expressive content.</p>
            <p>If any data appears inaccurate or creates a concern, we want to hear about it and review it promptly.</p>
          </div>
        </SectionCard>
      </div>

      <SectionCard title="Questions Or Concerns">
        <div className="space-y-4 text-sm leading-6 text-on-surface-variant">
          <p>
            For corrections, attribution concerns, or general questions about how data is
            being displayed, contact{" "}
            <a
              className="text-primary underline decoration-dotted"
              href={`mailto:${CONTACT_EMAIL}`}
              aria-label={`Email ${CONTACT_EMAIL}`}
            >
              {CONTACT_EMAIL}
            </a>
            .
          </p>
          <p>
            This page is informational only and should not be treated as legal advice.
          </p>
          <p>
            You can also use the{" "}
            <Link className="text-primary underline decoration-dotted" href="/contact">
              contact page
            </Link>{" "}
            for general feedback or corrections.
          </p>
        </div>
      </SectionCard>
    </div>
  );
}
