"""Centralized configuration package for JamBandNerd.

Example:
    from jambandnerd.config import SUPPORTED_BANDS, TOP_K_VALUES
"""

from __future__ import annotations

from .bands import (
    BAND_DISPLAY_NAMES,
    BAND_ID_COLUMNS,
    EXCLUDED_PREDICTION_SHOW_DATES,
    EXCLUDED_PREDICTION_SHOW_IDS,
    EXCLUDED_SONGS,
    SUPPORTED_BANDS,
)
from .data_collection import DATE_FORMATS, DEFAULT_CHUNK_SIZE, FETCH_CHUNK_SIZE
from .database import (
    SETLIST_ACCURACY_TABLE,
    SETLIST_PREDICTION_SONGS_TABLE,
    SETLIST_PREDICTIONS_TABLE,
    SETLIST_RESULTS_TABLE,
)
from .models import (
    BAND_EXCLUSION_WINDOWS,
    DEAL_EPOCHS,
    DEAL_L2_REGULARIZATION,
    DEAL_LEARNING_RATE,
    DEAL_MIN_PLAYS_THRESHOLD,
    DEAL_MIN_TRAINING_SHOWS,
    DEAL_RETRAIN_INTERVAL_DAYS,
    DEAL_TRAINING_WINDOW_SHOWS,
    EXCLUSION_WINDOW_DEFAULT,
    RETIREMENT_GAPS,
    TOP_K_VALUES,
)
from .pipeline import BACKOFF_FACTOR, DEFAULT_REQUEST_TIMEOUT, MAX_RETRIES

__all__ = [
    # bands.py
    "SUPPORTED_BANDS",
    "BAND_DISPLAY_NAMES",
    "BAND_ID_COLUMNS",
    "EXCLUDED_SONGS",
    "EXCLUDED_PREDICTION_SHOW_DATES",
    "EXCLUDED_PREDICTION_SHOW_IDS",
    # data_collection.py
    "DEFAULT_CHUNK_SIZE",
    "FETCH_CHUNK_SIZE",
    "DATE_FORMATS",
    # database.py
    "RAW_TABLE_SUFFIX",
    "SETLIST_PREDICTIONS_TABLE",
    "SETLIST_PREDICTION_SONGS_TABLE",
    "SETLIST_RESULTS_TABLE",
    "SETLIST_ACCURACY_TABLE",
    # models.py
    "TOP_K_VALUES",
    "EXCLUSION_WINDOW_DEFAULT",
    "BAND_EXCLUSION_WINDOWS",
    "RETIREMENT_GAPS",
    "DEAL_MIN_PLAYS_THRESHOLD",
    "DEAL_MIN_TRAINING_SHOWS",
    "DEAL_TRAINING_WINDOW_SHOWS",
    "DEAL_LEARNING_RATE",
    "DEAL_EPOCHS",
    "DEAL_L2_REGULARIZATION",
    "DEAL_RETRAIN_INTERVAL_DAYS",
    # pipeline.py
    "DEFAULT_REQUEST_TIMEOUT",
    "MAX_RETRIES",
    "BACKOFF_FACTOR",
]
