-- Create the 'games' table
CREATE TABLE public.games (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id integer NOT NULL UNIQUE,
    season integer NOT NULL,
    week integer NOT NULL,
    season_type text NOT NULL,
    start_date timestamptz NOT NULL,
    home_team text NOT NULL,
    home_points integer,
    away_team text NOT NULL,
    away_points integer,
    spread real,
    over_under real,
    completed boolean DEFAULT false,
    created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE public.games IS 'Stores game-level information, including schedules and results.';
ALTER TABLE public.games ENABLE ROW LEVEL SECURITY;

-- Create the 'plays' table
CREATE TABLE public.plays (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    play_id text NOT NULL UNIQUE,
    game_id integer NOT NULL REFERENCES public.games(game_id),
    drive_id text,
    offense text,
    defense text,
    period integer,
    clock text,
    down integer,
    distance integer,
    yard_line integer,
    play_type text,
    play_text text,
    ppa real,
    created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE public.plays IS 'Stores play-by-play data for each game.';
ALTER TABLE public.plays ENABLE ROW LEVEL SECURITY;

-- Create the 'predictions' table
CREATE TABLE public.predictions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id integer NOT NULL REFERENCES public.games(game_id),
    model_version text NOT NULL,
    predicted_spread real NOT NULL,
    predicted_over_under real NOT NULL,
    bet_on_spread text,
    bet_on_total text,
    created_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE public.predictions IS 'Stores model predictions for upcoming games.';
ALTER TABLE public.predictions ENABLE ROW LEVEL SECURITY;;
