create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$ language plpgsql;

create table if not exists public.billy_songs_raw (
  song_id bigint generated by default as identity primary key,
  song_uuid text,
  song_name text not null,
  original_artist text,
  original_artist_id text,
  times_played integer default 0,
  times_teased integer default 0,
  first_played date,
  last_played date,
  source_url text,
  source_hash text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists billy_songs_raw_song_name_idx on public.billy_songs_raw (song_name);
create unique index if not exists billy_songs_raw_song_uuid_idx on public.billy_songs_raw (song_uuid) where song_uuid is not null;
create unique index if not exists billy_songs_raw_source_hash_idx on public.billy_songs_raw (source_hash);

drop trigger if exists set_updated_at_billy_songs_raw on public.billy_songs_raw;
create trigger set_updated_at_billy_songs_raw
before update on public.billy_songs_raw
for each row execute function public.set_updated_at();;
