create table if not exists public.billy_shows_raw (
  show_id        bigint generated by default as identity primary key,
  source_uuid    uuid    not null unique,
  show_date      date    not null,
  venue_name     text,
  venue_city     text,
  venue_state    text,
  venue_country  text,
  source_url     text,
  source_hash    text    not null,
  created_at     timestamptz not null default timezone('utc', now()),
  updated_at     timestamptz not null default timezone('utc', now())
);

create index if not exists billy_shows_raw_show_date_idx on public.billy_shows_raw (show_date);

create table if not exists public.billy_setlists_raw (
  id             bigint generated by default as identity primary key,
  show_id        bigint not null references public.billy_shows_raw(show_id) on delete cascade,
  source_uuid    uuid,
  song_uuid      uuid,
  set_number     integer not null,
  song_position  integer not null,
  song_name      text    not null,
  is_segue       boolean not null default false,
  encore         boolean not null default false,
  song_notes     text,
  source_hash    text    not null,
  created_at     timestamptz not null default timezone('utc', now()),
  unique (show_id, set_number, song_position)
);

create index if not exists billy_setlists_raw_show_id_idx on public.billy_setlists_raw (show_id);
;
