-- Create single-model-per-band prediction tables.
-- These replace the multi-model next_show_* and completed_show_* tables as the
-- primary prediction and accuracy storage contract on the
-- feat/single-model-per-band branch.
-- model_slug is intentionally absent; each band has exactly one model.

create table if not exists public.setlist_predictions (
    id bigint not null generated by default as identity,
    created_at timestamptz not null default now(),
    band text not null,
    target_show_key text not null,
    target_show_date date not null,
    reference_date date not null,
    model_version text not null,
    generated_at timestamptz not null,
    top_k integer not null,
    predictions jsonb not null,
    constraint setlist_predictions_pkey primary key (id),
    constraint setlist_predictions_band_version_show_key
        unique (band, model_version, target_show_key),
    constraint setlist_predictions_top_k_positive check (top_k > 0)
);

create index if not exists setlist_predictions_band_version_generated_idx
    on public.setlist_predictions (
        band,
        model_version,
        generated_at desc
    );

create table if not exists public.setlist_prediction_songs (
    id bigint not null generated by default as identity,
    created_at timestamptz not null default now(),
    prediction_run_id bigint,
    band text not null,
    model_version text not null,
    target_show_key text not null,
    rank integer not null,
    song_name text not null,
    score double precision,
    prediction_payload jsonb not null,
    constraint setlist_prediction_songs_pkey primary key (id),
    constraint setlist_prediction_songs_run_fkey
        foreign key (prediction_run_id)
        references public.setlist_predictions (id)
        on delete cascade,
    constraint setlist_prediction_songs_band_version_show_rank_key
        unique (band, model_version, target_show_key, rank),
    constraint setlist_prediction_songs_rank_positive check (rank > 0)
);

create table if not exists public.setlist_results (
    id bigint not null generated by default as identity,
    created_at timestamptz not null default now(),
    band text not null,
    target_show_key text not null,
    target_show_date date not null,
    reference_date date not null,
    model_version text not null,
    generated_at timestamptz not null,
    top_k integer not null,
    predictions jsonb not null,
    actual_songs jsonb not null,
    actual_song_count integer not null,
    constraint setlist_results_pkey primary key (id),
    constraint setlist_results_band_version_show_key
        unique (band, model_version, target_show_key),
    constraint setlist_results_actual_song_count_positive
        check (actual_song_count > 0),
    constraint setlist_results_top_k_positive check (top_k > 0)
);

create index if not exists setlist_results_band_version_date_idx
    on public.setlist_results (
        band,
        model_version,
        target_show_date desc
    );

create table if not exists public.setlist_accuracy (
    id bigint not null generated by default as identity,
    created_at timestamptz not null default now(),
    band text not null,
    model_version text not null,
    show_id text not null,
    target_show_key text not null,
    show_date date not null,
    reference_date date not null,
    prediction_run_id bigint,
    actual_song_count integer not null,
    evaluated_at timestamptz not null,
    p10 double precision,
    p25 double precision,
    p50 double precision,
    recall_10 double precision,
    recall_25 double precision,
    recall_50 double precision,
    weighted_precision_score double precision,
    constraint setlist_accuracy_pkey primary key (id),
    constraint setlist_accuracy_run_fkey
        foreign key (prediction_run_id)
        references public.setlist_results (id)
        on delete cascade,
    constraint setlist_accuracy_band_version_show_key
        unique (band, model_version, target_show_key)
);

create index if not exists setlist_accuracy_band_version_date_idx
    on public.setlist_accuracy (
        band,
        model_version,
        show_date desc
    );

alter table public.setlist_predictions enable row level security;
alter table public.setlist_prediction_songs enable row level security;
alter table public.setlist_results enable row level security;
alter table public.setlist_accuracy enable row level security;

create policy setlist_predictions_public_read
    on public.setlist_predictions for select to anon using (true);
create policy setlist_prediction_songs_public_read
    on public.setlist_prediction_songs for select to anon using (true);
create policy setlist_results_public_read
    on public.setlist_results for select to anon using (true);
create policy setlist_accuracy_public_read
    on public.setlist_accuracy for select to anon using (true);

create policy setlist_predictions_service_all
    on public.setlist_predictions for all to service_role
    using (true) with check (true);
create policy setlist_prediction_songs_service_all
    on public.setlist_prediction_songs for all to service_role
    using (true) with check (true);
create policy setlist_results_service_all
    on public.setlist_results for all to service_role
    using (true) with check (true);
create policy setlist_accuracy_service_all
    on public.setlist_accuracy for all to service_role
    using (true) with check (true);
